model_name: emilyalsentzer/Bio_ClinicalBERT
data_path: data/processed/radiology_train_dataset.pt
output_dir: models/clinicalbert-qa-radiology
logging_dir: logs/radiology

learning_rate: 3e-5
per_device_train_batch_size: 16
per_device_eval_batch_size: 16
num_train_epochs: 3
weight_decay: 0.01
logging_steps: 50
save_total_limit: 2
report_to: tensorboard
seed: 42